### ISSUE TITLE
Notify TogglesUpdatedListeners after context is updated.

### ISSUE THREAD

**Issue by jagtejsodhi** [Unleash/unleash-android-proxy-sdk#36]
### Describe the feature request

Calling `UnleashClient.updateContext` triggers a call to `RefreshPolicy.refreshAsync()`, which fetches the latest toggles using the updated context. On successful fetch, the updated toggles are written to the toggle cache, but they should also trigger an update to all the `TogglesUpdatedListeners`.

The flow I described lives here: https://github.com/Unleash/unleash-android-proxy-sdk/blob/main/src/main/kotlin/io/getunleash/polling/RefreshPolicy.kt#L73-L79.

### Solution suggestions

Moving `AutoPollingPolicy.broadcastTogglesUpdated()` to `RefreshPolicy`, and calling the method right after [this line](https://github.com/Unleash/unleash-android-proxy-sdk/blob/main/src/main/kotlin/io/getunleash/polling/RefreshPolicy.kt#L76) should do the trick.

**Comment by fahmisdk6** [comment]
can confirm that the solution is working, are you guys open for pull request?

**Comment by fletchgqc** [comment]
I just spent a number of hours debugging this problem. I believe it's a bugfix, not an enhancement, because currently it's impossible to update the context if you work with listeners. Listeners will not receive the updated state of the toggles until the toggles change again.

Because refreshAsync writes the new state of the toggles to the cache, it means that future polls return false to [this check](https://github.com/Unleash/unleash-android-proxy-sdk/blob/17e9cf988cd5a0b9f937c5ec8fb8dd303faa69c7/src/main/kotlin/io/getunleash/polling/AutoPollingPolicy.kt#L81), meaning that listeners are not updated there, either.

In my particular situation, I create the client without the context and with PollingModes.manuallyStartPolling(). Later I add the context and then start polling, but since adding the context updates the cache as described above, the listeners never discover the state of the toggles.

**Comment by fletchgqc** [comment]
@jagtejsodhi I think your solution would do, though the ideal thing would be to call `AutoPollingPolicy.updateToggles()`, except you would want to do it non-blocking. 

Perhaps: `refreshAsync()` should be abstract in `RefreshPolicy`. `FilePollingPolicy` should have a NOOP implementation. `AutoPollingPolicy` should implement it with an async version of the logic which is currently in `updateToggles()`.

If you want to work with context changes and listeners before this is fixed, there are two possible workarounds I can think of:

1. Manually recreate the client every time you update the context. This has the effect of resetting the `ToggleCache`. You need to create and cache the client somewhere, and offer it to consumers as a Flow. Whenever the context changes, you call `client.close()` and then emit a new client on your flow.
2. During client creation, provide your own implementation of `ToggleCache`. In your implementation, add a method which clears the cache. Whenever you want to update the context, call:

```
updateContext(context).thenAccept { 
    toggleCache.clear()
    client.updateToggles()
}
```

**Comment by chriswk** [comment]
In #56 we move the broadcast of the toggles updated event into the update of the toggle cache in RefreshPolicy, so no matter how you update the RefreshPolicy you will now get the event broadcast. Sorry, this was an oversight.

**Comment by gastonfournier** [comment]
We've also taken this into consideration in the new SDK: https://github.com/Unleash/unleash-android
